var express = require('express')
var router = express.Router()
const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  swaggerDefinition: {
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  apis: ['index.js'],
};

const specs = swaggerJsdoc(options);
router.use('/', swaggerUi.serve, 
 swaggerUi.setup(specs)
);

module.exports = router